//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InspisPipe.SetIntegration {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SchoolResult", Namespace="http://schemas.datacontract.org/2004/07/Ness.CSI.WSIntegration.EPis.Impl")]
    [System.SerializableAttribute()]
    public partial class SchoolResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GradeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RedizoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryCode {
            get {
                return this.CategoryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryCodeField, value) != true)) {
                    this.CategoryCodeField = value;
                    this.RaisePropertyChanged("CategoryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Grade {
            get {
                return this.GradeField;
            }
            set {
                if ((this.GradeField.Equals(value) != true)) {
                    this.GradeField = value;
                    this.RaisePropertyChanged("Grade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Redizo {
            get {
                return this.RedizoField;
            }
            set {
                if ((this.RedizoField.Equals(value) != true)) {
                    this.RedizoField = value;
                    this.RaisePropertyChanged("Redizo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CampaignData", Namespace="http://schemas.datacontract.org/2004/07/Ness.CSI.WSIntegration.EPis.Impl")]
    [System.SerializableAttribute()]
    public partial class CampaignData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CampaignIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CampaignTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CampaignId {
            get {
                return this.CampaignIdField;
            }
            set {
                if ((this.CampaignIdField.Equals(value) != true)) {
                    this.CampaignIdField = value;
                    this.RaisePropertyChanged("CampaignId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CampaignType {
            get {
                return this.CampaignTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CampaignTypeField, value) != true)) {
                    this.CampaignTypeField = value;
                    this.RaisePropertyChanged("CampaignType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubjectInfo", Namespace="http://schemas.datacontract.org/2004/07/Ness.CSI.WSIntegration.EPis.Impl")]
    [System.SerializableAttribute()]
    public partial class SubjectInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdrAdditionalCharField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdrAdditionalNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdrBoroughField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdrCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdrCityPartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdrCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdrDistrictField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdrRegionUIVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdrStreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdrStreetNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdrZipCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactPersonNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FounderRedizoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FounderTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IcoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsClosedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RedizoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubjectA03IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdrAdditionalChar {
            get {
                return this.AdrAdditionalCharField;
            }
            set {
                if ((object.ReferenceEquals(this.AdrAdditionalCharField, value) != true)) {
                    this.AdrAdditionalCharField = value;
                    this.RaisePropertyChanged("AdrAdditionalChar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdrAdditionalNo {
            get {
                return this.AdrAdditionalNoField;
            }
            set {
                if ((object.ReferenceEquals(this.AdrAdditionalNoField, value) != true)) {
                    this.AdrAdditionalNoField = value;
                    this.RaisePropertyChanged("AdrAdditionalNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdrBorough {
            get {
                return this.AdrBoroughField;
            }
            set {
                if ((object.ReferenceEquals(this.AdrBoroughField, value) != true)) {
                    this.AdrBoroughField = value;
                    this.RaisePropertyChanged("AdrBorough");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdrCity {
            get {
                return this.AdrCityField;
            }
            set {
                if ((object.ReferenceEquals(this.AdrCityField, value) != true)) {
                    this.AdrCityField = value;
                    this.RaisePropertyChanged("AdrCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdrCityPart {
            get {
                return this.AdrCityPartField;
            }
            set {
                if ((object.ReferenceEquals(this.AdrCityPartField, value) != true)) {
                    this.AdrCityPartField = value;
                    this.RaisePropertyChanged("AdrCityPart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdrCountry {
            get {
                return this.AdrCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.AdrCountryField, value) != true)) {
                    this.AdrCountryField = value;
                    this.RaisePropertyChanged("AdrCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdrDistrict {
            get {
                return this.AdrDistrictField;
            }
            set {
                if ((object.ReferenceEquals(this.AdrDistrictField, value) != true)) {
                    this.AdrDistrictField = value;
                    this.RaisePropertyChanged("AdrDistrict");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdrRegionUIV {
            get {
                return this.AdrRegionUIVField;
            }
            set {
                if ((object.ReferenceEquals(this.AdrRegionUIVField, value) != true)) {
                    this.AdrRegionUIVField = value;
                    this.RaisePropertyChanged("AdrRegionUIV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdrStreet {
            get {
                return this.AdrStreetField;
            }
            set {
                if ((object.ReferenceEquals(this.AdrStreetField, value) != true)) {
                    this.AdrStreetField = value;
                    this.RaisePropertyChanged("AdrStreet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdrStreetNo {
            get {
                return this.AdrStreetNoField;
            }
            set {
                if ((object.ReferenceEquals(this.AdrStreetNoField, value) != true)) {
                    this.AdrStreetNoField = value;
                    this.RaisePropertyChanged("AdrStreetNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdrZipCode {
            get {
                return this.AdrZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AdrZipCodeField, value) != true)) {
                    this.AdrZipCodeField = value;
                    this.RaisePropertyChanged("AdrZipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactPersonName {
            get {
                return this.ContactPersonNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactPersonNameField, value) != true)) {
                    this.ContactPersonNameField = value;
                    this.RaisePropertyChanged("ContactPersonName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FounderRedizo {
            get {
                return this.FounderRedizoField;
            }
            set {
                if ((this.FounderRedizoField.Equals(value) != true)) {
                    this.FounderRedizoField = value;
                    this.RaisePropertyChanged("FounderRedizo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FounderTypeId {
            get {
                return this.FounderTypeIdField;
            }
            set {
                if ((this.FounderTypeIdField.Equals(value) != true)) {
                    this.FounderTypeIdField = value;
                    this.RaisePropertyChanged("FounderTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ico {
            get {
                return this.IcoField;
            }
            set {
                if ((object.ReferenceEquals(this.IcoField, value) != true)) {
                    this.IcoField = value;
                    this.RaisePropertyChanged("Ico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsClosed {
            get {
                return this.IsClosedField;
            }
            set {
                if ((this.IsClosedField.Equals(value) != true)) {
                    this.IsClosedField = value;
                    this.RaisePropertyChanged("IsClosed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Redizo {
            get {
                return this.RedizoField;
            }
            set {
                if ((this.RedizoField.Equals(value) != true)) {
                    this.RedizoField = value;
                    this.RaisePropertyChanged("Redizo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubjectA03Id {
            get {
                return this.SubjectA03IdField;
            }
            set {
                if ((this.SubjectA03IdField.Equals(value) != true)) {
                    this.SubjectA03IdField = value;
                    this.RaisePropertyChanged("SubjectA03Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SynchronizeResult", Namespace="http://schemas.datacontract.org/2004/07/Ness.CSI.WSIntegration.EPis.Impl")]
    [System.SerializableAttribute()]
    public partial class SynchronizeResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChangedCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NewCreatedCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChangedCount {
            get {
                return this.ChangedCountField;
            }
            set {
                if ((this.ChangedCountField.Equals(value) != true)) {
                    this.ChangedCountField = value;
                    this.RaisePropertyChanged("ChangedCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NewCreatedCount {
            get {
                return this.NewCreatedCountField;
            }
            set {
                if ((this.NewCreatedCountField.Equals(value) != true)) {
                    this.NewCreatedCountField = value;
                    this.RaisePropertyChanged("NewCreatedCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SchoolIzoDefinition", Namespace="http://schemas.datacontract.org/2004/07/Ness.CSI.WSIntegration.EPis.Impl")]
    [System.SerializableAttribute()]
    public partial class SchoolIzoDefinition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] FieldIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IzoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SubjectA03IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubjectA37IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] FieldIds {
            get {
                return this.FieldIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldIdsField, value) != true)) {
                    this.FieldIdsField = value;
                    this.RaisePropertyChanged("FieldIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Izo {
            get {
                return this.IzoField;
            }
            set {
                if ((this.IzoField.Equals(value) != true)) {
                    this.IzoField = value;
                    this.RaisePropertyChanged("Izo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SubjectA03Id {
            get {
                return this.SubjectA03IdField;
            }
            set {
                if ((this.SubjectA03IdField.Equals(value) != true)) {
                    this.SubjectA03IdField = value;
                    this.RaisePropertyChanged("SubjectA03Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubjectA37Id {
            get {
                return this.SubjectA37IdField;
            }
            set {
                if ((this.SubjectA37IdField.Equals(value) != true)) {
                    this.SubjectA37IdField = value;
                    this.RaisePropertyChanged("SubjectA37Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeCode {
            get {
                return this.TypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeCodeField, value) != true)) {
                    this.TypeCodeField = value;
                    this.RaisePropertyChanged("TypeCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldDefinition", Namespace="http://schemas.datacontract.org/2004/07/Ness.CSI.WSIntegration.EPis.Impl")]
    [System.SerializableAttribute()]
    public partial class FieldDefinition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int A18IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsClosedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCode1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCode2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCode3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCode4Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int A18Id {
            get {
                return this.A18IdField;
            }
            set {
                if ((this.A18IdField.Equals(value) != true)) {
                    this.A18IdField = value;
                    this.RaisePropertyChanged("A18Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsClosed {
            get {
                return this.IsClosedField;
            }
            set {
                if ((this.IsClosedField.Equals(value) != true)) {
                    this.IsClosedField = value;
                    this.RaisePropertyChanged("IsClosed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCode1 {
            get {
                return this.SubCode1Field;
            }
            set {
                if ((object.ReferenceEquals(this.SubCode1Field, value) != true)) {
                    this.SubCode1Field = value;
                    this.RaisePropertyChanged("SubCode1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCode2 {
            get {
                return this.SubCode2Field;
            }
            set {
                if ((object.ReferenceEquals(this.SubCode2Field, value) != true)) {
                    this.SubCode2Field = value;
                    this.RaisePropertyChanged("SubCode2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCode3 {
            get {
                return this.SubCode3Field;
            }
            set {
                if ((object.ReferenceEquals(this.SubCode3Field, value) != true)) {
                    this.SubCode3Field = value;
                    this.RaisePropertyChanged("SubCode3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCode4 {
            get {
                return this.SubCode4Field;
            }
            set {
                if ((object.ReferenceEquals(this.SubCode4Field, value) != true)) {
                    this.SubCode4Field = value;
                    this.RaisePropertyChanged("SubCode4");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SetIntegration.IWSEPis")]
    public interface IWSEPis {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEPis/GetCampaignResults", ReplyAction="http://tempuri.org/IWSEPis/GetCampaignResultsResponse")]
        InspisPipe.SetIntegration.SchoolResult[] GetCampaignResults(long campaignId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEPis/GetCampaignResults", ReplyAction="http://tempuri.org/IWSEPis/GetCampaignResultsResponse")]
        System.Threading.Tasks.Task<InspisPipe.SetIntegration.SchoolResult[]> GetCampaignResultsAsync(long campaignId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEPis/GetFinishedCampaigns", ReplyAction="http://tempuri.org/IWSEPis/GetFinishedCampaignsResponse")]
        InspisPipe.SetIntegration.CampaignData[] GetFinishedCampaigns();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEPis/GetFinishedCampaigns", ReplyAction="http://tempuri.org/IWSEPis/GetFinishedCampaignsResponse")]
        System.Threading.Tasks.Task<InspisPipe.SetIntegration.CampaignData[]> GetFinishedCampaignsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEPis/GetOpenedCampaigns", ReplyAction="http://tempuri.org/IWSEPis/GetOpenedCampaignsResponse")]
        InspisPipe.SetIntegration.CampaignData[] GetOpenedCampaigns();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEPis/GetOpenedCampaigns", ReplyAction="http://tempuri.org/IWSEPis/GetOpenedCampaignsResponse")]
        System.Threading.Tasks.Task<InspisPipe.SetIntegration.CampaignData[]> GetOpenedCampaignsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEPis/GetAllCampaignsForSchool", ReplyAction="http://tempuri.org/IWSEPis/GetAllCampaignsForSchoolResponse")]
        InspisPipe.SetIntegration.CampaignData[] GetAllCampaignsForSchool(long redizo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEPis/GetAllCampaignsForSchool", ReplyAction="http://tempuri.org/IWSEPis/GetAllCampaignsForSchoolResponse")]
        System.Threading.Tasks.Task<InspisPipe.SetIntegration.CampaignData[]> GetAllCampaignsForSchoolAsync(long redizo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEPis/GetRegisteredSchoolsRedizo", ReplyAction="http://tempuri.org/IWSEPis/GetRegisteredSchoolsRedizoResponse")]
        int[] GetRegisteredSchoolsRedizo(long campaignId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEPis/GetRegisteredSchoolsRedizo", ReplyAction="http://tempuri.org/IWSEPis/GetRegisteredSchoolsRedizoResponse")]
        System.Threading.Tasks.Task<int[]> GetRegisteredSchoolsRedizoAsync(long campaignId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEPis/RegisterSchoolToCampaign", ReplyAction="http://tempuri.org/IWSEPis/RegisterSchoolToCampaignResponse")]
        bool RegisterSchoolToCampaign(long campaignId, int[] schollRedizo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEPis/RegisterSchoolToCampaign", ReplyAction="http://tempuri.org/IWSEPis/RegisterSchoolToCampaignResponse")]
        System.Threading.Tasks.Task<bool> RegisterSchoolToCampaignAsync(long campaignId, int[] schollRedizo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEPis/SynchronizeSchools", ReplyAction="http://tempuri.org/IWSEPis/SynchronizeSchoolsResponse")]
        InspisPipe.SetIntegration.SynchronizeResult SynchronizeSchools(InspisPipe.SetIntegration.SubjectInfo[] schoolToSynchronize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEPis/SynchronizeSchools", ReplyAction="http://tempuri.org/IWSEPis/SynchronizeSchoolsResponse")]
        System.Threading.Tasks.Task<InspisPipe.SetIntegration.SynchronizeResult> SynchronizeSchoolsAsync(InspisPipe.SetIntegration.SubjectInfo[] schoolToSynchronize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEPis/SynchronizeSchoolFounders", ReplyAction="http://tempuri.org/IWSEPis/SynchronizeSchoolFoundersResponse")]
        InspisPipe.SetIntegration.SynchronizeResult SynchronizeSchoolFounders(InspisPipe.SetIntegration.SubjectInfo[] founderToSynchronize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEPis/SynchronizeSchoolFounders", ReplyAction="http://tempuri.org/IWSEPis/SynchronizeSchoolFoundersResponse")]
        System.Threading.Tasks.Task<InspisPipe.SetIntegration.SynchronizeResult> SynchronizeSchoolFoundersAsync(InspisPipe.SetIntegration.SubjectInfo[] founderToSynchronize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEPis/SynchronizeSchoolIZO", ReplyAction="http://tempuri.org/IWSEPis/SynchronizeSchoolIZOResponse")]
        InspisPipe.SetIntegration.SynchronizeResult SynchronizeSchoolIZO(InspisPipe.SetIntegration.SchoolIzoDefinition[] izoDefinition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEPis/SynchronizeSchoolIZO", ReplyAction="http://tempuri.org/IWSEPis/SynchronizeSchoolIZOResponse")]
        System.Threading.Tasks.Task<InspisPipe.SetIntegration.SynchronizeResult> SynchronizeSchoolIZOAsync(InspisPipe.SetIntegration.SchoolIzoDefinition[] izoDefinition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEPis/SynchronizeFields", ReplyAction="http://tempuri.org/IWSEPis/SynchronizeFieldsResponse")]
        InspisPipe.SetIntegration.SynchronizeResult SynchronizeFields(InspisPipe.SetIntegration.FieldDefinition[] fieldDefs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEPis/SynchronizeFields", ReplyAction="http://tempuri.org/IWSEPis/SynchronizeFieldsResponse")]
        System.Threading.Tasks.Task<InspisPipe.SetIntegration.SynchronizeResult> SynchronizeFieldsAsync(InspisPipe.SetIntegration.FieldDefinition[] fieldDefs);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSEPisChannel : InspisPipe.SetIntegration.IWSEPis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSEPisClient : System.ServiceModel.ClientBase<InspisPipe.SetIntegration.IWSEPis>, InspisPipe.SetIntegration.IWSEPis {
        
        public WSEPisClient() {
        }
        
        public WSEPisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSEPisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSEPisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSEPisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public InspisPipe.SetIntegration.SchoolResult[] GetCampaignResults(long campaignId) {
            return base.Channel.GetCampaignResults(campaignId);
        }
        
        public System.Threading.Tasks.Task<InspisPipe.SetIntegration.SchoolResult[]> GetCampaignResultsAsync(long campaignId) {
            return base.Channel.GetCampaignResultsAsync(campaignId);
        }
        
        public InspisPipe.SetIntegration.CampaignData[] GetFinishedCampaigns() {
            return base.Channel.GetFinishedCampaigns();
        }
        
        public System.Threading.Tasks.Task<InspisPipe.SetIntegration.CampaignData[]> GetFinishedCampaignsAsync() {
            return base.Channel.GetFinishedCampaignsAsync();
        }
        
        public InspisPipe.SetIntegration.CampaignData[] GetOpenedCampaigns() {
            return base.Channel.GetOpenedCampaigns();
        }
        
        public System.Threading.Tasks.Task<InspisPipe.SetIntegration.CampaignData[]> GetOpenedCampaignsAsync() {
            return base.Channel.GetOpenedCampaignsAsync();
        }
        
        public InspisPipe.SetIntegration.CampaignData[] GetAllCampaignsForSchool(long redizo) {
            return base.Channel.GetAllCampaignsForSchool(redizo);
        }
        
        public System.Threading.Tasks.Task<InspisPipe.SetIntegration.CampaignData[]> GetAllCampaignsForSchoolAsync(long redizo) {
            return base.Channel.GetAllCampaignsForSchoolAsync(redizo);
        }
        
        public int[] GetRegisteredSchoolsRedizo(long campaignId) {
            return base.Channel.GetRegisteredSchoolsRedizo(campaignId);
        }
        
        public System.Threading.Tasks.Task<int[]> GetRegisteredSchoolsRedizoAsync(long campaignId) {
            return base.Channel.GetRegisteredSchoolsRedizoAsync(campaignId);
        }
        
        public bool RegisterSchoolToCampaign(long campaignId, int[] schollRedizo) {
            return base.Channel.RegisterSchoolToCampaign(campaignId, schollRedizo);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterSchoolToCampaignAsync(long campaignId, int[] schollRedizo) {
            return base.Channel.RegisterSchoolToCampaignAsync(campaignId, schollRedizo);
        }
        
        public InspisPipe.SetIntegration.SynchronizeResult SynchronizeSchools(InspisPipe.SetIntegration.SubjectInfo[] schoolToSynchronize) {
            return base.Channel.SynchronizeSchools(schoolToSynchronize);
        }
        
        public System.Threading.Tasks.Task<InspisPipe.SetIntegration.SynchronizeResult> SynchronizeSchoolsAsync(InspisPipe.SetIntegration.SubjectInfo[] schoolToSynchronize) {
            return base.Channel.SynchronizeSchoolsAsync(schoolToSynchronize);
        }
        
        public InspisPipe.SetIntegration.SynchronizeResult SynchronizeSchoolFounders(InspisPipe.SetIntegration.SubjectInfo[] founderToSynchronize) {
            return base.Channel.SynchronizeSchoolFounders(founderToSynchronize);
        }
        
        public System.Threading.Tasks.Task<InspisPipe.SetIntegration.SynchronizeResult> SynchronizeSchoolFoundersAsync(InspisPipe.SetIntegration.SubjectInfo[] founderToSynchronize) {
            return base.Channel.SynchronizeSchoolFoundersAsync(founderToSynchronize);
        }
        
        public InspisPipe.SetIntegration.SynchronizeResult SynchronizeSchoolIZO(InspisPipe.SetIntegration.SchoolIzoDefinition[] izoDefinition) {
            return base.Channel.SynchronizeSchoolIZO(izoDefinition);
        }
        
        public System.Threading.Tasks.Task<InspisPipe.SetIntegration.SynchronizeResult> SynchronizeSchoolIZOAsync(InspisPipe.SetIntegration.SchoolIzoDefinition[] izoDefinition) {
            return base.Channel.SynchronizeSchoolIZOAsync(izoDefinition);
        }
        
        public InspisPipe.SetIntegration.SynchronizeResult SynchronizeFields(InspisPipe.SetIntegration.FieldDefinition[] fieldDefs) {
            return base.Channel.SynchronizeFields(fieldDefs);
        }
        
        public System.Threading.Tasks.Task<InspisPipe.SetIntegration.SynchronizeResult> SynchronizeFieldsAsync(InspisPipe.SetIntegration.FieldDefinition[] fieldDefs) {
            return base.Channel.SynchronizeFieldsAsync(fieldDefs);
        }
    }
}
